version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=api
    - MYSQL_USER=api
    - MYSQL_PASSWORD=api
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/create-table-macapa.sql:/docker-entrypoint-initdb.d/create-table-macapa.sql

  postgresql:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
    volumes:
        - ./data/create-table-varejao.sql:/docker-entrypoint-initdb.d/create-table-varejao.sql

  node:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - mysql
      - postgresql
